$(document).ready(function(){
    $('.owl-carousel').owlCarousel({
        loop:true,
        autoplay:true,
        autoplayTimeout:2500,
        margin:15,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            600:{
                items:3
            },
            1000:{
                items:3
            }
        }
    });
})
    $('.insta-carousel').owlCarousel({
        loop:true,
        autoplay:true,
        autoplayTimeout:4500,
        margin:0,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            600:{
                items:4
            },
            1000:{
                items:4
            }
        }
    })

    $('.birthday-carousel').owlCarousel({
        loop:true,
        autoplay:true,
        autoplayTimeout:2500,
        margin:15,
        rtl:true,
        nav:false,
        responsive:{
            0:{
                items:1
            },
            768:{
                items:2
            },
            600:{
                items:3
            },
            1000:{
                items:3
            }
        }
    });
